### ISSUE TITLE
E021-02 includes invalid keyword VARING

### ISSUE THREAD

**Issue by Schultzer** [elliotchance/sqltest#8]
The keyword `VARING` is not included in the BNF.txt https://github.com/elliotchance/sqltest/blob/master/standards/2016/bnf.txt nor does it exists in the newest spec 2023. I've been assuming that all these files was generated, but now I'm wondering how it possible for there to be a typo in a generated file.

Do you remember if you wrote some of these tests manually?

```yml
sql: CREATE TABLE TN ( A { CHAR VARING | CHARACTER VARYING | VARCHAR } [ <left paren> <character length> <right paren> ] )
override:
  length: 8
```
